version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - keploy-network

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - keploy-network

  keploy:
    image: ghcr.io/keploy/keploy:v2.4.5
    container_name: keploy
    command: [
      "record",
      "--cmd-type", "docker-compose",
      "--proxy-port", "16789",
      "--network-name", "keploy-network",
      "--container-name", "crud_keploy-test-backend-1"
    ]
    depends_on:
      - backend
    ports:
      - "16789:16789"
    networks:
      - keploy-network

networks:
  keploy-network:
