name: Keploy API Tests

on:
  push: { branches: [main] }
  pull_request:

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: |
          nohup npx nodemon index.js &
          sleep 5

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=+nwjpM222AumgOF13A== && keploy test-suite --app=bc1e9a2f-be3c-4b7c-9d07-a5fe53fe578f --base-path https://522a-2405-201-a009-951-259d-4585-e3e8-7c7b.ngrok-free.app --cloud