name: Keploy API Tests

on:
  push: { branches: [main] }
  pull_request:

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: |
          nohup npx nodemon index.js &
          sleep 5

      - run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite \
            --app=YOUR_APP_ID \
            --base-path http://localhost:8000 \
            --cloud
